### ISSUE TITLE
Docker routing doesn't seem to be working

### ISSUE THREAD

**Issue by russkel** [thrnz/docker-wireguard-pia#1]
Hello @thrnz,

First thanks for this image, it's exactly what I was going to put together. However, for the life of me I can't get routing from other containers through the VPN working correctly.

They have routing set up correctly:
```
/ # ip r
default via 172.17.0.2 dev eth0 
172.17.0.0/16 dev eth0 scope link  src 172.17.0.3 
/ # 
```
Where `172.17.0.2` is the container running docker-wireguard-pia. 

```
version: '3'
services:
    vpn:
        # networks:
            # wg-vpn:
        network_mode: "bridge"
        image: docker-wireguard-pia
        volumes:
            # Auth token is stored here
            - pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - pia-shared:/pia-shared
        # privileged is needing for adding the 0.0.0.0/0 route
        privileged: true
        cap_add:
            - NET_ADMIN
            # SYS_MODULE might not be needed with a 5.6+ kernel?
            - SYS_MODULE
        environment:
            # - LOCAL_NETWORK=172.17.0.0/16
            - ALLOW_DOCKER=1
            - LOC=swiss
            - USER=fffffff
            - PASS=ffff
            - KEEPALIVE=25
            #- VPNDNS=8.8.8.8,8.8.4.4
            - USEMODERN=1
            # - PORT_FORWARDING=1
        # May as well disable ipv6. Should be blocked by iptables anyway.
        sysctls:
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        

volumes:
    pia:
    pia-shared:
```
So the VPN container is on the bridge network, and it is pingable.

On the docker-wireguard-pia container:

```
Chain INPUT (policy DROP 2 packets, 152 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   99 12124 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  lo     any     anywhere             anywhere            
    1    84 ACCEPT     all  --  eth0   any     172.17.0.0/16        anywhere            

Chain FORWARD (policy DROP 473 packets, 31594 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   88 10328 ACCEPT     all  --  any    any     anywhere             anywhere             mark match 0xca6c
   22  1729 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  any    lo      anywhere             anywhere            
    0     0 ACCEPT     all  --  any    eth0    anywhere             172.17.0.0/16       
   34  2248 ACCEPT     all  --  any    wg0     anywhere             anywhere            
```
It seems the FORWARD policy is dropping the packets (I notice this increases as I ping).

Any thoughts?

**Comment by thrnz** [comment]
I'd not considered using it as a gateway for other containers when I put this together, so it might need some more changes to get that working. I've left all forwarded traffic blocked by default, and that nat rule would indeed need changing - it was inherited from the container I based it on and probably isn't achieving much at the moment.

ALLOW_DOCKER just allows input/output to the bridge network, so something like a reverse proxy in another container can still access a vpn attached container. I wanted everything to be blocked by default, and to only explicitly allow whats needed, but it's  kind of redundant and should probably just be allowed by default - if the vpn container needed isolating from other containers on the bridge network, it wouldn't be attached in the first place.

In my case, I'm just sharing the vpn with other containers using 'network_mode', so something like this:
```

version: '3'
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            - pia:/pia
        privileged: true
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - LOC=swiss
            - USER=xxx
            - PASS=xxx
            - USEMODERN=1
        
    other-container-with-vpn-access:
        image: alpine 
        network_mode: "service:vpn"

volumes:
    pia:
```
