### ISSUE TITLE
How to expose a port to local LAN?

### ISSUE THREAD

**Issue by ngugcx** [thrnz/docker-wireguard-pia#102]
I attach a socks5 server container to docker-wireguard-pia container and expose socks5 port, and hope my other machines in local LAN can use the socks5 service.
I can access it on the container host by localhost: curl -x socks5h://localhost:10001 https://icanhazip.com
But fail to do that by ip addr: curl -x socks5h://172.25.204.214:10001 https://icanhazip.com

How can I expose the port to local LAN? thanks.

My docker-compose.yml:
```
version: "3" 
services:

  pia-10001:
    container_name: pia-10001
    image: docker.io/thrnz/docker-wireguard-pia
    cap_add:
      - NET_ADMIN
      # SYS_MODULE might not be needed with a 5.6+ kernel?
      # - SYS_MODULE
    # If the kernel module isn't available, mounting the tun device may be necessary for userspace implementations
    #devices:
    #  - /dev/net/tun:/dev/net/tun
    ports:
      - 10001:1080
    environment:
      # The following env vars are required:
      - LOC=Norway
      - USER=mmmmmmm
      - PASS=nnnnnnn
      # The rest are optional:
      #- LOCAL_NETWORK=192.168.1.0/24
      #- KEEPALIVE=25
      #- VPNDNS=8.8.8.8,8.8.4.4
      #- PORT_FORWARDING=1
    sysctls:
      # The wg-quick script tries to set this when setting up routing, however this requires running the container
      # with the --privileged flag set. Setting it here instead if needed means the container can be run with lower
      # privileges. This only needs setting if strict reverse path filtering (rp_filter=1) is used.
      - net.ipv4.conf.all.src_valid_mark=1
      # May as well disable ipv6. Should be blocked anyway.
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    # The container has no recovery logic. Use a healthcheck to catch disconnects.
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  socks5-10001:
    container_name: socks5-10001
    image: docker.io/serjs/go-socks5-proxy
    network_mode: service:pia-10001
```
