### ISSUE TITLE
Could not resolve host: serverlist.piaservers.com

### ISSUE THREAD

**Issue by SnowDrifterr** [thrnz/docker-wireguard-pia#105]
New issue popped up after updating today. Previous version present on Feb 5th worked.

Issue persists if I try the testing branch as well.

Logs:
```
Sun Apr 21 17:13:55 UTC 2024: Falling back to iptables-legacy
Fetching next-gen PIA server list
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
curl: (6) Could not resolve host: serverlist.piaservers.net
Error reading signature file /tmp/tmp.kOjkmh
Failed to verify server list
Sun Apr 21 17:15:08 UTC 2024: Failed to generate WireGuard config
Sun Apr 21 17:15:08 UTC 2024: Fatal error
```

Compose config: 
```yaml
services:
  wgpia:
    image: thrnz/docker-wireguard-pia
    container_name: wgpia
    networks:
      - ${NETTOOLS}
    volumes:
      - ${DOCKERCONFDIR}/pia:/pia
      - ${DOCKERCONFDIR}/pia-shared:/pia-shared
    cap_add:
      - NET_ADMIN
    environment:
      - LOC=ca_vancouver
      - USER=**
      - PASS=**
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 30
    ports:
      - 58846:58846
      - 58946:58946
      - 8112:8112
      - 8118:8118
    restart: always
```
