### ISSUE TITLE
Multiple containers that share same port

### ISSUE THREAD

**Issue by hockeygoalie35** [thrnz/docker-wireguard-pia#107]
Hi! Using your example docker compose with the reverse proxy works perfectly, but what happens if I want to use two containers that insist on using the same port? And worse, they both want to use port 80? Since I’m using ‘networkmode: “service:vpn”, o can’t map the ports at a container level, only at the wireguard-PIA level. Any thoughts?

**Comment by thrnz** [comment]
If the two services are hardcoded to bind to port 80, then all I can think of would be running a second vpn container for the second service. They could still be attached to the same Docker bridge network if they need to communicate with each other, although it might be a bit fiddly as Docker's internal dns would no longer be used for resolving container names.

Something like this maybe:
```
services:
    vpn1:
        image: thrnz/docker-wireguard-pia
        volumes:
            - pia-dat:/pia
        ports:
            - 80:80
        cap_add:
            - NET_ADMIN
        environment:
            - LOCAL_NETWORK=192.168.1.0/24
            - LOC=swiss
            - USER=xxxx
            - PASS=xxxx
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1

    service1:
        image: some-docker-image
        network_mode: "service:vpn1"

    vpn2:
        image: thrnz/docker-wireguard-pia
        volumes:
            - pia-dat2:/pia
        ports:
            - 81:80
        cap_add:
            - NET_ADMIN
        environment:
            - LOCAL_NETWORK=192.168.1.0/24
            - LOC=swiss
            - USER=xxxx
            - PASS=xxxx
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1

    service2:
        image: some-docker-image
        network_mode: "service:vpn2"

volumes:
    pia-dat:
    pia-dat2:
```

Have you got an example compose showing what you're trying to do? If the issue isn't what I'm thinking of, then there might be an easier way of working around it.
