### ISSUE TITLE
Porf Fowardding: curl timeout when trying to get PF Token

### ISSUE THREAD

**Issue by Olanzer** [thrnz/docker-wireguard-pia#112]
Asustor Nimbustor (5404T). Has a kernel update for wireguard, but it's not really natively supported. I can connect to wg fine with Port Forwarding turned off:

```
Sat Aug  3 10:31:16 UTC 2024: Falling back to iptables-legacy
Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: aus_perth, cn: perth403, ip: 179.61.228.50
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Port forwarding is available at this location
Successfully generated /etc/wireguard/wg0.conf
Sat Aug  3 10:31:19 UTC 2024: Bringing up WireGuard interface wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.49.254.68 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
could not detect a useable init system
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
iptables-restore v1.8.10 (legacy): iptables-restore: unable to initialize table 'raw'
Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
interface: wg0
  public key: aYbigtIzBrVfyCRKCXyCKHweQNgUJglDHiKbOnIEbBc=
  private key: (hidden)
  listening port: 33960
  fwmark: 0xca6c
peer: AiKBWW2oJahzloBQe1vqFOoxD17HLVjsdEfzgoi9ESM=
  endpoint: 179.61.228.50:1337
  allowed ips: 0.0.0.0/0
Sat Aug  3 10:31:19 UTC 2024: WireGuard successfully started
Sat Aug  3 10:31:19 UTC 2024: Allowing network access to 192.168.176.2/20 on eth0
Warning: Extension mark revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Sat Aug  3 10:31:19 UTC 2024: Firewall enabled: Blocking non-WireGuard traffic
Sat Aug  3 10:31:19 UTC 2024: Allowing network access to 10.69.182.160/27 on eth0
Sat Aug  3 10:31:19 UTC 2024: Adding route to 10.69.182.160/27
```

But when I turn Port Forwarding to 1, this happens:

```
Sat Aug  3 10:24:11 UTC 2024: Falling back to iptables-legacy
Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: aus_perth, cn: perth405, ip: 179.61.228.183
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Port forwarding is available at this location
Successfully generated /etc/wireguard/wg0.conf
Sat Aug  3 10:24:13 UTC 2024: Bringing up WireGuard interface wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.54.188.151 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
could not detect a useable init system
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
iptables-restore v1.8.10 (legacy): iptables-restore: unable to initialize table 'raw'
Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
interface: wg0
  public key: HWsS/MRoE+GMBaylAgc6A1NJ9Ei5foXfQbhqFcJI+Gw=
  private key: (hidden)
  listening port: 59649
  fwmark: 0xca6c
peer: k/6P7abuf0zIGAHj3Sk/0TjBL78CLt1zdcI/dI+TGDE=
  endpoint: 179.61.228.183:1337
  allowed ips: 0.0.0.0/0
Sat Aug  3 10:24:13 UTC 2024: WireGuard successfully started
Sat Aug  3 10:24:13 UTC 2024: Allowing network access to 192.168.144.2/20 on eth0
Warning: Extension mark revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
Sat Aug  3 10:24:13 UTC 2024: Firewall enabled: Blocking non-WireGuard traffic
Sat Aug  3 10:24:13 UTC 2024: Starting port forward script
Sat Aug  3 10:24:13 UTC 2024: Verifying API requests. CN: perth405
Sat Aug  3 10:24:13 UTC 2024: Getting PF token
curl: (28) Failed to connect to perth405 port 19999 after 30002 ms: Timeout was reached
curl: (28) Failed to connect to perth405 port 19999 after 30002 ms: Timeout was reached
curl: (28) Failed to connect to perth405 port 19999 after 30002 ms: Timeout was reached
curl: (28) Failed to connect to perth405 port 19999 after 30002 ms: Timeout was reached
curl: (28) Failed to connect to perth405 port 19999 after 30002 ms: Timeout was reached
```

Docker-compose (tried running the testing version to see if that helps but no dice)

```
services:

  pia:
      image: thrnz/docker-wireguard-pia:testing
      cap_add:
          - NET_ADMIN
          # SYS_MODULE might not be needed with a 5.6+ kernel?
          - SYS_MODULE
      # If the kernel module isn't available, mounting the tun device may be necessary for userspace implementations
      #devices:
      #  - /dev/net/tun:/dev/net/tun
      environment:
          # The following env vars are required:
          - LOC=aus_perth
          - USER=(Username)
          - PASS=(Password)
          - PORT_FORWARDING=1
          - PORT_PERSIST=1

       
      sysctls:
          # The wg-quick script tries to set this when setting up routing, however this requires running the container
          # with the --privileged flag set. Setting it here instead if needed means the container can be run with lower
          # privileges. This only needs setting if strict reverse path filtering (rp_filter=1) is used.
          - net.ipv4.conf.all.src_valid_mark=1
          # May as well disable ipv6. Should be blocked anyway.
          - net.ipv6.conf.default.disable_ipv6=1
          - net.ipv6.conf.all.disable_ipv6=1
          - net.ipv6.conf.lo.disable_ipv6=1
      # The container has no recovery logic. Use a healthcheck to catch disconnects.
      healthcheck:
          test: ping -c 1 www.google.com || exit 1
          interval: 30s
          timeout: 10s
          retries: 3
      volumes:
          # Auth token is stored here
          - /volume1/Docker/pia:/pia
          # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
          - /volume1/Docker/pia/pia-shared:/pia-shared
  
      
    # Example of another service sharing the VPN
    # If this service needs LAN access then LOCAL_NETWORK must be set appropriatley on the vpn container
    # Forwared ports should also be set on the vpn container if needed rather than this one in
    # order to access from the LAN
    # It may be preferable to use a reverse proxy connected via the docker bridge network instead
    # to keep the vpn isolated from the LAN
    # other-service:
       # image: some-other-image
        # Other services can share the VPN using 'network_mode'
        # See https://docs.docker.com/engine/reference/run/#network-container and
        # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
        # network_mode: "service:vpn"

    # Other containers can access the forwarded port number via /pia-shared/port.dat
    # Here's an example of a bare-bones 'helper' container that passes the forwarded port to Deluge
    # See https://gist.github.com/thrnz/dcbaa0af66c70af8e302a1c7eb75484a
    # deluge-port-helper:
    #    build: /path/to/deluge-port-helper
    #    volumes:
    #        - pia-shared:/pia-shared:ro
    #        - /path/to/deluge/conf:/deluge/conf
    #    network_mode: "service:vpn"
    #    depends_on:
    #        - vpn
    #        - other-service
```

I also tried other locations like aus_melbourne and overseas but AFAIK wireguard works on almost all locations with PF turned on anyway.
