### ISSUE TITLE
Unable to access qBittorrent UI through LAN on port 8080

### ISSUE THREAD

**Issue by lumen-novum** [thrnz/docker-wireguard-pia#113]
```
qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /mnt/data/qbittorrent/appdata:/config
      #- /path/to/downloads:/downloads #optional
    network_mode: service:pia
    depends_on:
      - pia
    restart: unless-stopped
  pia:
    image: thrnz/docker-wireguard-pia
    volumes:
      - /mnt/data/pia/scripts:/pia-scripts
      - /mnt/data/qbittorrent/appdata/qBittorrent:/qbit-config
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
    environment:
      # The following env vars are required:
      - LOC=bo_bolivia-pf
      - LOCAL_NETWORK=10.0.0.0/24
      - USER=xxxxxxxxxxx
      - PASS=xxxxxxxxxxx
      - PORT_FORWARDING=1
      - PORT_FILE_CLEANUP=1
      - PORT_SCRIPT=/pia-scripts/qbit-port.sh
      - PORT_FATAL=1
      - EXIT_ON_FATAL=1
    sysctls:
      # The wg-quick script tries to set this when setting up routing, however this requires running the container
      # with the --privileged flag set. Setting it here instead if needed means the container can be run with lower
      # privileges. This only needs setting if strict reverse path filtering (rp_filter=1) is used.
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    # The container has no recovery logic. Use a healthcheck to catch disconnects.
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
```

How do I expose port 8080 on my LAN? (to access qBittorrent) I tried to use socat but I couldn't get it to work.
