### ISSUE TITLE
How to set --privileged in Compose?

### ISSUE THREAD

**Issue by zilexa** [thrnz/docker-wireguard-pia#12]
Host: Ubuntu 20.04

The container starts successfully, I am running transmission and checked with the testfile from torguard what my IP is in Transmission, its PIA. So all is well. However in the logfile (checked via Portainer) I notice: 
`sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system`

And in your docker-compose.yml example the comment says: 
`        # wg-quick fails to set this without --privileged, so set it here instead if needed`
I Googled a bit but I do not see how to set --privileged via docker-compose. I believe it can only be done via docker command?

Also I noticed in your docker-compose.yml you forgot to add a `ports` section as an example, to allow web interfaces. And a name for the container: 

```
container_name: VPN
(...)
    ports:
      - 9091:9091 
```
Otherwise if ppl copy/paste the example file, it will be named `docker_vpn_1`. Not an issue of course, but might as well give it a nice name :)

**Comment by thrnz** [comment]
From [here](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir),  you can use ```privileged: true``` in a compose file if needed.

AFAICT it's only needed when wg-quick sets ```net.ipv4.conf.all.src_valid_mark=1```, so I thought it might be a better idea to set it directly using the compose file and ignoring that error rather than running with elevated privileges.

**Comment by zilexa** [comment]
Thanks, it works now. For future reference, this is the full version. 

```
  vpn:
    container_name: VPN
    image: thrnz/docker-wireguard-pia
    volumes:
        # Auth token is stored here
        - $USERDIR/docker/vpn/pia:/pia
        # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
        - $USERDIR/docker/vpn/pia-shared:/pia-shared
    cap_add:
        - NET_ADMIN
        # SYS_MODULE might not be needed with a 5.6+ kernel?
        #- SYS_MODULE
    # Mounting the tun device may be necessary for userspace implementations
    #devices:
    #  - /dev/net/tun:/dev/net/tun
    environment:
        - LOCAL_NETWORK=192.168.88.0/24,10.6.0.1/24
        - LOC=de-frankfurt
        - USER=$VPN_USER_PIA
        - PASS=$VPN_PW_PIA
        #- KEEPALIVE=25
        #- VPNDNS=8.8.8.8,8.8.4.4
        - PORT_FORWARDING=1
        - PORT_PERSIST=1
        #- WG_USERSPACE=1
    privileged: true
    sysctls:
        # wg-quick fails to set this without --privileged, so set it here instead if needed
        - net.ipv4.conf.all.src_valid_mark=1
        # May as well disable ipv6. Should be blocked anyway.
        - net.ipv6.conf.default.disable_ipv6=1
        - net.ipv6.conf.all.disable_ipv6=1
        - net.ipv6.conf.lo.disable_ipv6=1
    # The container has no recovery logic. Use a healthcheck to catch disconnects.
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 30s
        timeout: 10s
        retries: 3
    ports:
      - 9091:9091 #Transmission
      #- 6789:6789 #NZBget
```
