### ISSUE TITLE
Parse error + Healthcheck error

### ISSUE THREAD

**Issue by AndrewPro** [thrnz/docker-wireguard-pia#125]
Hello, when I copy and pase the code form [here](https://github.com/thrnz/docker-wireguard-pia/blob/master/docker-compose.yml), the healthcheck gives me problems.
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.vpn.healthcheck value 'start_interval' does not match any of the regexes: '^x-'
```

Here is the fix

```yml
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "www.google.com"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 30s
```
## Parse error 
```
Creating pia ... done
Attaching to pia
pia    | Tue Jan 14 06:20:53 UTC 2025: Generating auth token
pia    | jq: parse error: Invalid numeric literal at line 1, column 5
pia    | Failed to acquire new auth token. Response:
pia    | HTTP Token: Access denied.
pia    | Tue Jan 14 06:20:54 UTC 2025: Failed to acquire new auth token
pia    | Tue Jan 14 06:20:54 UTC 2025: Fatal error
```
Here is the `docker-compose`:
```yml
services:
  vpn:
    image: thrnz/docker-wireguard-pia
    container_name: pia
    volumes:
      - pia:/pia
      - pia-shared:/pia-shared
    cap_add:
      - NET_ADMIN
    environment:
      - LOC=swiss
      - USER=p6317748
      - PASS=epFq7oA9^B514()2p^99rZ#
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
      
volumes:
  pia:
  pia-shared:
```

I am unable to currently use the docker container, but I am trying to find a solution. I will try to keep this updated.
