### ISSUE TITLE
Firewall issue causing slow P2P speed even with forwarded port

### ISSUE THREAD

**Issue by paperman5** [thrnz/docker-wireguard-pia#129]
Hi, I have been trying to fix an issue I've been having with slow speeds for quite a while and I have not been able to solve it, probably because of something I don't understand with Docker and firewalls.

I am trying to set up qBittorrent to go through this VPN container with wireguard using docker-compose, and the provided example configurations were very helpful and everything seems to be working fine except for the very low speeds (20Mbit down / 1Mbit up on a 100Mbit down&up connection). After a bunch of experimenting/troubleshooting I *think* it has to do with the firewall on the host machine, but I could be wrong. Here is the relevant section of my `docker-compose.yml` file.

```
services:
  pia-vpn:
    image: thrnz/docker-wireguard-pia
    volumes:
      # Auth token is stored here
      - pia:/pia
      # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
      - pia-shared:/pia-shared
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LOC=ca_toronto
      - USER=xxxxx
      - PASS=xxxxx
      - PORT_FORWARDING=1
      - PORT_PERSIST=1
      - LOCAL_NETWORK=192.168.0.0/24
    ports:
      - "8000:8000/tcp"            # access to http control server
      - "8080:8080"                # qbittorrent webui
    sysctls:
      # The wg-quick script tries to set this when setting up routing, however this requires running the container
      # with the --privileged flag set. Setting it here instead if needed means the container can be run with lower
      # privileges. This only needs setting if strict reverse path filtering (rp_filter=1) is used.
      - net.ipv4.conf.all.src_valid_mark=1
      # May as well disable ipv6. Should be blocked anyway.
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
      # The container has no recovery logic. Use a healthcheck to catch disconnects.
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    network_mode: "service:pia-vpn"
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=xxxx
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent-config:/config
      - /tank/media/downloads:/media/downloads
    restart: unless-stopped

volumes:
  pia:
  pia-shared:
```

After starting the containers, I check which port is being forwarded from the logs and then forward that port from my router to the machine running the containers. I also have a script set up to change the port in qBittorrent after it is received from the VPN.

The reason I think it is an issue with the host firewall is because connection requests time out both through netcat (`nc -z -v -w5 public_ip port`) and through online port checkers. If I add the forwarded VPN port to the compose config (using `PORT_PERSIST=1` and restarting after obtaining the port), the port refuses the connection instead of timing out. Finally, if I use the desktop qBittorrent application, find the port that application uses and forward it through my router, that port appears as open to the public. Netcat can also connect to the qBittorrent web UI port via local IP (+public IP if I forward the port through my router).

Maybe I am misunderstanding how this is all supposed to be working, but it appears as though most peers are not able to connect through this port even though it should be forwarded, although some peers are still able to connect somehow, probably through a different method. If anyone has an idea of what might be the issue or has other diagnostics/tests I could run to find the issue that would be helpful, as I mostly just know enough about networking to get myself in trouble... XD
