### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by lastb0isct** [thrnz/docker-wireguard-pia#15]
Here is the error I'm getting:
```
Tue Jan 26 17:11:27 UTC 2021: WireGuard successfully started,
Tue Jan 26 17:11:27 UTC 2021: Firewall enabled: Blocking non-WireGuard traffic,
Tue Jan 26 17:11:27 UTC 2021: Starting port forward script,
Tue Jan 26 17:11:27 UTC 2021: Verifying API requests. CN: losangeles416,
Tue Jan 26 17:11:27 UTC 2021: Getting PF token,
curl: (7) Failed to connect to losangeles416 port 19999: Connection refused,
Tue Jan 26 17:11:27 UTC 2021: getSignature error,
Tue Jan 26 17:11:27 UTC 2021: Fatal error,
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
```
My compose.yml
```  
wireguardvpn:
    image: thrnz/docker-wireguard-pia
    container_name: wireguardvpn
    volumes:
      # Auth token is stored here
      - pia:/pia
      # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
      - pia-shared:/pia-shared
    cap_add:
      - ALL
      # SYS_MODULE might not be needed with a 5.6+ kernel?
      #- SYS_MODULE
      # Mounting the tun device may be necessary for userspace implementations
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      #- LOCAL_NETWORK=192.168.1.0/24
      - LOC=us_california
      - USER=pxxxxx
      - PASS=xxxxxxxx
      #- KEEPALIVE=25
      - VPNDNS=1.1.1.1,1.0.0.1
      - PORT_FORWARDING=1
      #- WG_USERSPACE=1
    sysctls:
      # wg-quick fails to set this without --privileged, so set it here instead if needed
      - net.ipv4.conf.all.src_valid_mark=1
      # May as well disable ipv6. Should be blocked anyway.
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    # The container has no recovery logic. Use a healthcheck to catch disconnects.
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
```
