### ISSUE TITLE
unclear how to config deluge port forwarding

### ISSUE THREAD

**Issue by N4p0l3on** [thrnz/docker-wireguard-pia#16]
I have wireguard-pia and deluge working fine, but I don't upload, I think I misconfigured my compose docker, I'm a beginner and I'm lost, can somebody help me pls. ty !

```
#===============================================================================
#=============================== V.2.0 =========================================
#===============================================================================
version: '3.7'
services:
#===============================================================================
    vpn:
        image: thrnz/docker-wireguard-pia
        container_name: vpn
        volumes:
            - ${ROOT}/pia:/pia
            - ${ROOT}/pia-shared:/pia-shared
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - LOC=swiss
            - USER=pxxxxxxxx
            - "PASS=xxxxxxxxx"
            #- LOCAL_NETWORK=192.168.1.0/24
            #- KEEPALIVE=25
            #- VPNDNS=8.8.8.8,8.8.4.4
            - PORT_FORWARDING=1
            #- WG_USERSPACE=1
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        ports:
            - 9111:9000 # portainer.io
            - 9983:80 # Organizrr
            - 4545:4545
            - 6767:6767
            - 6789:6789
            - 8989:8989
            - 7878:7878      
            - 3579:3579
            - 8112:8112 # Deluge
#===============================================================================
    deluge:
        container_name: deluge
        image: linuxserver/deluge:latest
        restart: always
        network_mode: service:vpn 
        depends_on:
          - vpn    
        environment:
          - PUID=${PUID} 
          - PGID=${PGID} 
          - TZ=${TZ} 
        volumes:
          - ${ROOT}/downloads:/downloads 
          - ${ROOT}/config/deluge:/config 
#===============================================================================
    deluge-port-helper:
        container_name: deluge_port_forwarding
        build: /media/homemedia/pia/pia
        volumes:
            - ${ROOT}/pia-shared:/pia-shared
            - ${ROOT}/config/deluge:/config 
        network_mode: "service:vpn"
        depends_on:
            - vpn
            - deluge
```

**Comment by N4p0l3on** [comment]
![1](https://user-images.githubusercontent.com/78302673/106384350-507b5f80-63c2-11eb-94a2-8ec80339f76c.png)

**Comment by N4p0l3on** [comment]
![1](https://user-images.githubusercontent.com/78302673/106384376-7acd1d00-63c2-11eb-9c05-0bcd9b881008.png)
![Uploading Capture du 2021-01-31 13-44-32.png…]()

**Comment by N4p0l3on** [comment]
![1](https://user-images.githubusercontent.com/78302673/106384396-92a4a100-63c2-11eb-9185-d46f8c7a2ebf.png)
![Capture du 2021-01-31 13-44-32](https://user-images.githubusercontent.com/78302673/106384397-92a4a100-63c2-11eb-9586-e4de26a5a72b.png)

**Comment by thrnz** [comment]
I'm no longer using Deluge, but if you're using [this](https://gist.github.com/thrnz/dcbaa0af66c70af8e302a1c7eb75484a) example helper container as-is, then it expects the config to be mounted at ```/deluge/config``` rather than ```/config```. So:

```
    deluge-port-helper:
        container_name: deluge_port_forwarding
        build: /media/homemedia/pia/pia
        volumes:
            - ${ROOT}/pia-shared:/pia-shared
            - ${ROOT}/config/deluge:/deluge/config
        network_mode: "service:vpn"
        depends_on:
            - vpn
            - deluge
```

From memory, using ```deluge-console``` was a bit unstable at times, so it might need some retry logic added if something unexpected happens.

Alternatively, if you're not having much luck scripting it, you can set the env var ```PORT_PERSIST=1``` on the vpn container, and then just enter the forwarded port manually into Deluge. IIRC PIA will give the same forwarded port number for two months if done this way.
