### ISSUE TITLE
Fatal error after recreating container 

### ISSUE THREAD

**Issue by zilexa** [thrnz/docker-wireguard-pia#19]
Ubuntu 20.10 host. 
I did not change my compose file, but did delete the container+non-persistent volumes and had to create it again via compose up. Unfortunately, that lead to this: 

```
Mon Apr 26 09:52:23 UTC 2021: Generating auth token
Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: swiss, cn: zurich408, ip: 212.102.37.8
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
WG key registration failed
Mon Apr 26 09:52:24 UTC 2021: Failed to generate WireGuard config
Mon Apr 26 09:52:24 UTC 2021: Fatal error   
```

I tried again after deleting my persistent folder `pia-shared:`, same issue. 
I did not change my compose file except for the port, from `9090:9090` to `9090:8080`.

How can I fix this? 

My compose: 
```
  vpn-proxy:
    container_name: vpn-proxy
    image: thrnz/docker-wireguard-pia
    restart: always
    networks: 
      - vpn-proxy
    volumes:
      # Auth token is stored here
      - $DOCKERDIR/vpn/pia:/pia
      # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
      - $DOCKERDIR/vpn/pia-shared:/pia-shared
    cap_add:
      - NET_ADMIN
      #- SYS_MODULE might not be needed with a 5.6+ kernel?
      #- SYS_MODULE
      # Mounting the tun device may be necessary for userspace implementations
      #devices:
      #- /dev/net/tun:/dev/net/tun
    environment:
      LOCAL_NETWORK: 192.168.88.0/24,10.6.0.1/24
      LOC: swiss
      USER: $VPN_USER_PIA
      PASS: $VPN_PW_PIA
      #KEEPALIVE: 25
      #VPNDNS: 8.8.8.8,8.8.4.4
      PORT_FORWARDING: 1
      PORT_PERSIST: 
      #WG_USERSPACE: 1
    privileged: 'true'
    sysctls:
      # wg-quick fails to set this without --privileged, so set it here instead if needed
      - net.ipv4.conf.all.src_valid_mark=1
      # May as well disable ipv6. Should be blocked anyway.
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    # The container has no recovery logic. Use a healthcheck to catch disconnects.
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 9090:8080 #Qbittorrent webUI
```
