### ISSUE TITLE
Some questions about docker and Yacht

### ISSUE THREAD

**Issue by Jorman** [thrnz/docker-wireguard-pia#22]
Hi, finally I'm changing my NAS, and now I can run Docker.
I Installed Yacht then I tried to import the example docker-compose file
```
version: '3'
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            # Auth token is stored here
            - /yacht/AppData/Config/pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - /yacht/AppData/Config/pia:/pia-shared
        cap_add:
            - NET_ADMIN
            # SYS_MODULE might not be needed with a 5.6+ kernel?
            - SYS_MODULE
        # Mounting the tun device may be necessary for userspace implementations
        devices:
            - /dev/net/tun:/dev/net/tun
        environment:
            # The following env vars are required:
            - LOC=italy
            - USER=xxx
            - PASS=xxx
            # The rest are optional:
            #- LOCAL_NETWORK=192.168.1.0/24
            - KEEPALIVE=25
            #- VPNDNS=8.8.8.8,8.8.4.4
            - PORT_FORWARDING=1
            #- WG_USERSPACE=1
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 30s
            timeout: 10s
            retries: 3

    # Example of another service sharing the VPN
    #other-service:
        #image: linuxserver/qbittorrent
        # Other services can share the VPN using 'network_mode'
        #network_mode: "service:vpn"

    # Other containers can access the forwarded port number via /pia-shared/port.dat
    # Here's an example of a bare-bones 'helper' container that passes the forwarded port to Deluge
    # See https://gist.github.com/thrnz/dcbaa0af66c70af8e302a1c7eb75484a
    #deluge-port-helper:
        #build: /path/to/deluge-port-helper
        #volumes:
            #- pia-shared:/pia-shared:ro
            #- /path/to/deluge/conf:/deluge/conf
        #network_mode: "service:vpn"
        #depends_on:
            #- vpn
            #- other-service

volumes:
    pia:
    pia-shared:
```
And this's the log of the container
```
Sun May 30 16:23:08 UTC 2021: Generating auth token
Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: italy, cn: milano403, ip: 156.146.41.70
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Port forwarding is available at this location
Successfully generated /etc/wireguard/wg0.conf
Sun May 30 16:23:11 UTC 2021: Bringing up WireGuard interface wg0
[#] ip link add wg0 type wireguard
RTNETLINK answers: Not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go wg0
┌───────────────────────────────────────────────────┐
│                                                   │
│   Running this software on Linux is unnecessary,  │
│   because the Linux kernel has built-in first     │
│   class support for WireGuard, which will be      │
│   faster, slicker, and better integrated. For     │
│   information on installing the kernel module,    │
│   please visit: <https://wireguard.com/install>.  │
│                                                   │
└───────────────────────────────────────────────────┘
[#] wg setconf wg0 /dev/fd/63
```
I see one device under the container
![1](https://user-images.githubusercontent.com/5203988/120119927-a1e20280-c19a-11eb-8eb2-efb5e1fd74a0.PNG)
But I don't see any file for PF and I think wg is not connected

The final purpose is to use WG with qBittorrent with PF, so qBittorrent network is set to this
![2](https://user-images.githubusercontent.com/5203988/120120558-474aa580-c19e-11eb-8cac-573a9cdbdbaa.PNG)

Anyone know how can I check and fix if wg is running and up?

J

**Comment by Jorman** [comment]
Ok, little update.
I upgraded the kernel to bpo 5.10 so now the logs show that the connection is ok, I think:
```
$ docker logs 2e97f81ee924
Sun May 30 22:30:53 UTC 2021: Generating auth token
Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: italy, cn: milano403, ip: 156.146.41.89
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Port forwarding is available at this location
Successfully generated /etc/wireguard/wg0.conf
Sun May 30 22:30:54 UTC 2021: Bringing up WireGuard interface wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.24.183.58 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] iptables-restore -n

interface: wg0
  public key: ****=
  private key: (hidden)
  listening port: 48079
  fwmark: 0xca6c

peer: ****=
  endpoint: 156.146.41.89:1337
  allowed ips: 0.0.0.0/0
  transfer: 0 B received, 148 B sent
  persistent keepalive: every 25 seconds

Sun May 30 22:30:55 UTC 2021: WireGuard successfully started
Sun May 30 22:30:55 UTC 2021: Allowing network access to 172.18.0.3/16 on eth0
Sun May 30 22:30:55 UTC 2021: Firewall enabled: Blocking non-WireGuard traffic
Sun May 30 22:30:55 UTC 2021: Allowing network access to 10.0.0.0/24
Sun May 30 22:30:55 UTC 2021: Adding route to 10.0.0.0/24
Sun May 30 22:30:55 UTC 2021: Starting port forward script
Sun May 30 22:30:55 UTC 2021: Verifying API requests. CN: milano403
Sun May 30 22:30:55 UTC 2021: Getting PF token
Sun May 30 22:31:01 UTC 2021: Obtained PF token. Expires at 2021-08-01T10:31:57.650370059Z
Sun May 30 22:31:01 UTC 2021: Server accepted PF bind
Sun May 30 22:31:01 UTC 2021: Forwarding on port 25069
Sun May 30 22:31:01 UTC 2021: Running /scripts/pf_success.sh
Sun May 30 22:31:01 UTC 2021: Allowing incoming traffic on port 25069
Sun May 30 22:31:01 UTC 2021: Rebind interval: 900 seconds
Sun May 30 22:31:01 UTC 2021: Port dumped to /pia-shared/port.dat
Sun May 30 22:31:01 UTC 2021: This script should remain running to keep the forwarded port alive
Sun May 30 22:31:01 UTC 2021: Press Ctrl+C to exit
Mon May 31 16:11:12 UTC 2021: Port forward rebinding stopped. The port will likely close soon.
Mon May 31 16:11:12 UTC 2021: Shutting down WireGuard
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
[#] resolvconf -d wg0 -f
[#] iptables-restore -n
Fetching next-gen PIA server list
curl: (6) Could not resolve host: serverlist.piaservers.net
Verified OK
Verified server list
Registering public key with PIA endpoint; id: italy, cn: milano402, ip: 156.146.41.28
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Port forwarding is available at this location
Successfully generated /etc/wireguard/wg0.conf
Mon May 31 16:12:32 UTC 2021: Bringing up WireGuard interface wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.27.243.61 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] iptables-restore -n

interface: wg0
  public key: ****=
  private key: (hidden)
  listening port: 42431
  fwmark: 0xca6c

peer: ****=
  endpoint: 156.146.41.28:1337
  allowed ips: 0.0.0.0/0
  transfer: 0 B received, 148 B sent
  persistent keepalive: every 25 seconds

Mon May 31 16:12:32 UTC 2021: WireGuard successfully started
Mon May 31 16:12:32 UTC 2021: Allowing network access to 172.18.0.2/16 on eth0
Mon May 31 16:12:32 UTC 2021: Firewall enabled: Blocking non-WireGuard traffic
Mon May 31 16:12:32 UTC 2021: Allowing network access to 10.0.0.0/24
Mon May 31 16:12:32 UTC 2021: Adding route to 10.0.0.0/24
Mon May 31 16:12:32 UTC 2021: Starting port forward script
Mon May 31 16:12:32 UTC 2021: Verifying API requests. CN: milano402
Mon May 31 16:12:32 UTC 2021: Getting PF token
Mon May 31 16:12:38 UTC 2021: Obtained PF token. Expires at 2021-08-02T04:12:01.687719629Z
Mon May 31 16:12:38 UTC 2021: Server accepted PF bind
Mon May 31 16:12:38 UTC 2021: Forwarding on port 29062
Mon May 31 16:12:38 UTC 2021: Running /scripts/pf_success.sh
Mon May 31 16:12:38 UTC 2021: Allowing incoming traffic on port 29062
Mon May 31 16:12:38 UTC 2021: Rebind interval: 900 seconds
Mon May 31 16:12:38 UTC 2021: Port dumped to /pia-shared/port.dat
Mon May 31 16:12:38 UTC 2021: This script should remain running to keep the forwarded port alive
Mon May 31 16:12:38 UTC 2021: Press Ctrl+C to exit
Mon May 31 16:12:43 UTC 2021: Port forward rebinding stopped. The port will likely close soon.
Mon May 31 16:12:43 UTC 2021: Shutting down WireGuard
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
[#] resolvconf -d wg0 -f
[#] iptables-restore -n
Fetching next-gen PIA server list
curl: (6) Could not resolve host: serverlist.piaservers.net
Verified OK
Verified server list
Registering public key with PIA endpoint; id: italy, cn: milano402, ip: 156.146.41.15
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Port forwarding is available at this location
Successfully generated /etc/wireguard/wg0.conf
Mon May 31 17:09:20 UTC 2021: Bringing up WireGuard interface wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.14.182.22 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] iptables-restore -n

interface: wg0
  public key: ****=
  private key: (hidden)
  listening port: 46932
  fwmark: 0xca6c

peer: ****=
  endpoint: 156.146.41.15:1337
  allowed ips: 0.0.0.0/0
  transfer: 0 B received, 148 B sent
  persistent keepalive: every 25 seconds

Mon May 31 17:09:20 UTC 2021: WireGuard successfully started
Mon May 31 17:09:21 UTC 2021: Allowing network access to 172.18.0.2/16 on eth0
Mon May 31 17:09:21 UTC 2021: Firewall enabled: Blocking non-WireGuard traffic
Mon May 31 17:09:21 UTC 2021: Allowing network access to 10.0.0.0/24
Mon May 31 17:09:21 UTC 2021: Adding route to 10.0.0.0/24
Mon May 31 17:09:21 UTC 2021: Starting port forward script
Mon May 31 17:09:21 UTC 2021: Verifying API requests. CN: milano402
Mon May 31 17:09:21 UTC 2021: Getting PF token
Mon May 31 17:09:26 UTC 2021: Obtained PF token. Expires at 2021-08-02T05:08:49.993893547Z
Mon May 31 17:09:26 UTC 2021: Server accepted PF bind
Mon May 31 17:09:26 UTC 2021: Forwarding on port 44274
Mon May 31 17:09:26 UTC 2021: Running /scripts/pf_success.sh
Mon May 31 17:09:26 UTC 2021: Allowing incoming traffic on port 44274
Mon May 31 17:09:26 UTC 2021: Rebind interval: 900 seconds
Mon May 31 17:09:26 UTC 2021: Port dumped to /pia-shared/port.dat
Mon May 31 17:09:26 UTC 2021: This script should remain running to keep the forwarded port alive
Mon May 31 17:09:26 UTC 2021: Press Ctrl+C to exit
```
Except these errors
`sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system`
`curl: (6) Could not resolve host: serverlist.piaservers.net`

But to me seems that qBittorrent don't use the wireguard net, see this
```
$ docker network inspect wireguard-pia_default
[
    {
        "Name": "wireguard-pia_default",
        "Id": "4899ca1952eb8d62df59ba92e339976112928a00b6c6605a82e454be50c1ac81",
        "Created": "2021-05-30T18:23:02.762323034+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "2e97f81ee92401a18ca777647cd3ce14bb78124381ba91b4b264f09437a3550d": {
                "Name": "wireguard-pia_vpn_1",
                "EndpointID": "c835a5b28727d91c4215db0f6f16f3ac353e30a425467225cdbf587a0093d162",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "ecd57e5b25b1f932e0481560293e660cc67b5f49d31f239cf02f09cbf44b4761": {
                "Name": "qbittorrent",
                "EndpointID": "ded54bac56b0b3cad3eee23177636610b640117b8f9cebf57acccac4f2cf2cdd",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "wireguard-pia",
            "com.docker.compose.version": "1.28.4"
        }
    }
]
```
What I do wrong?
Ps, I want to remove the project because every time I want to edit the docker image I lost sysctls settings, I don't know why.

J

**Comment by Jorman** [comment]
Small update, after a lot of unsuccessful attempts, I think to get pia-wg and qbittorrent working I need to create a docker-compose file, so I tried and I make this but is not 100% working:
```
version: '3'
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        container_name: pia-wireguard-vpn-proxy
        hostname: pia-wg-vpn-proxy
        volumes:
            # Auth token is stored here
            - /yacht/AppData/Config/pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - /yacht/AppData/Config/pia:/pia-shared
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        # Mounting the tun device may be necessary for userspace implementations
        #devices:
        #  - /dev/net/tun:/dev/net/tun
        environment:
            - PUID=1000
            - PGID=100
            - LOC=italy
            - USER=***
            - PASS=***
            - PORT_FORWARDING=1
            - PORT_PERSIST=1
            - FIREWALL=0
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        ports:
            - 6881:6881
            - 6881:6881/udp
            - 8080:8080
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped

    # Example of another service sharing the VPN
    qbittorrent:
        image: ghcr.io/linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Rome
            - WEBUI_PORT=8080
        volumes:
            - /yacht/AppData/Config/qBittorrent:/config
            - /data/Download:/downloads
        network_mode: "service:vpn"
        depends_on: [ "vpn", ]
        restart: unless-stopped
```
I can't understand why is not working like expected, let me explain what happen.
My LAN is under 10.0.0.0
1. If I run the docker-compose like the example, and I connect to both qbittorrent and pia-wireguard container and I try to curl ipinfo.io all is ok but I can't establish a connection to webui of qbittorrent, so 10.0.0.100:8080 is not available
```
docker ps
CONTAINER ID   IMAGE                             COMMAND          CREATED          STATUS                             PORTS                                                                                                                             NAMES
be0f70f377c5   ghcr.io/linuxserver/qbittorrent   "/init"          25 seconds ago   Up 24 seconds                                                                                                                                                        qbittorrent
cae53c42eacd   thrnz/docker-wireguard-pia        "/scripts/run"   26 seconds ago   Up 24 seconds (health: starting)   0.0.0.0:6881->6881/tcp, :::6881->6881/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:6881->6881/udp, :::8080->8080/tcp, :::6881->6881/udp   pia-wireguard-vpn-proxy
86b527dfde58   selfhostedpro/yacht               "/init"          47 hours ago     Up 47 hours                        0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                                         stupefied_stonebraker

# root @ debian in ~ [22:40:19]
$ docker exec -it cae53c42eacd bash
bash-5.1# ip r
default via 192.168.32.1 dev eth0
192.168.32.0/20 dev eth0 proto kernel scope link src 192.168.32.2
bash-5.1# curl ipinfo.io
{
  "ip": "156.146.41.208",
  "hostname": "unn-156-146-41-208.cdn77.com",
  "city": "Milan",
  "region": "Lombardy",
  "country": "IT",
  "loc": "45.4643,9.1895",
  "org": "AS60068 Datacamp Limited",
  "postal": "20121",
  "timezone": "Europe/Rome",
  "readme": "https://ipinfo.io/missingauth"
}bash-5.1# exit
exit

# root @ debian in ~ [22:40:56]
$ docker exec -it be0f70f377c5 bash
root@pia-wg-vpn-proxy:/# ip r
bash: ip: command not found
root@pia-wg-vpn-proxy:/# curl ipinfo.io
{
  "ip": "156.146.41.208",
  "hostname": "unn-156-146-41-208.cdn77.com",
  "city": "Milan",
  "region": "Lombardy",
  "country": "IT",
  "loc": "45.4643,9.1895",
  "org": "AS60068 Datacamp Limited",
  "postal": "20121",
  "timezone": "Europe/Rome",
  "readme": "https://ipinfo.io/missingauth"
```
So I added - LOCAL_NETWORK=10.0.0.0/24 to docker-compose file and run it again, but now if I execute a curl to ipinfo.io from container
```
$ docker ps
CONTAINER ID   IMAGE                             COMMAND          CREATED          STATUS                             PORTS                                                                                                                             NAMES
ebae15c3c310   ghcr.io/linuxserver/qbittorrent   "/init"          13 seconds ago   Up 12 seconds                                                                                                                                                        qbittorrent
08589ac5072f   thrnz/docker-wireguard-pia        "/scripts/run"   13 seconds ago   Up 12 seconds (health: starting)   0.0.0.0:6881->6881/tcp, :::6881->6881/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:6881->6881/udp, :::8080->8080/tcp, :::6881->6881/udp   pia-wireguard-vpn-proxy
86b527dfde58   selfhostedpro/yacht               "/init"          47 hours ago     Up 47 hours                        0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                                         stupefied_stonebraker

# root @ debian in ~ [22:50:16]
$ docker exec -it 08589ac5072f bash
bash-5.1# curl ipinfo.io
curl: (6) Could not resolve host: ipinfo.io
bash-5.1# exit
```
But in this case I can reach the qbittorrent webui, so 10.0.0.100:8080 is available

Anyone knows what I do wrong?

J

**Comment by thrnz** [comment]
I think PIA's DNS servers are 10.0.0.242 and 10.0.0.243, which would be inaccessible with ```LOCAL_NETWORK=10.0.0.0/24```. You might need to use another DNS by setting ```VPNDNS=8.8.8.8, 8.8.4.4```. Hopefully thats enough to gets things working as expected.

**Comment by Jorman** [comment]
Yesssssssss, this's the trick!
I added manula dns and local network too, just because I also use a vpn to connect from outside and gues what? Is under 10.8.* so

Now I only have to set-up the port forward for this, I'm looking at this example on your docker-compose file
```
    # Other containers can access the forwarded port number via /pia-shared/port.dat
    # Here's an example of a bare-bones 'helper' container that passes the forwarded port to Deluge
    # See https://gist.github.com/thrnz/dcbaa0af66c70af8e302a1c7eb75484a
    deluge-port-helper:
        build: /path/to/deluge-port-helper
        volumes:
            - pia-shared:/pia-shared:ro
            - /path/to/deluge/conf:/deluge/conf
        network_mode: "service:vpn"
        depends_on:
            - vpn
            - other-service
```
Any advice for qBittorrent?
Do you know if exists a possibility to run a pre/post script for the docker execution? I'm totally new to this system.

**Comment by Jorman** [comment]
Ok, this docker-compose for qbittorrent + wireguard-pia is working, I put it here, maybe can be helpful for someone:
```
version: '3'
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        container_name: pia-wireguard-vpn-proxy
        hostname: pia-wg-vpn-proxy
        volumes:
            # Auth token is stored here
            - /yacht/AppData/Config/pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - /yacht/AppData/Config/pia:/pia-shared
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=100
            - LOC=italy
            - USER=***
            - PASS=***
            - PORT_FORWARDING=1
            - PORT_PERSIST=1
            - FIREWALL=0
            - VPNDNS=1.1.1.1, 1.0.0.1
            - LOCAL_NETWORK=10.0.0.0/24, 10.8.0.0/29
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        ports:
            - 6881:6881
            - 6881:6881/udp
            - 8081:8081
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped

    # Example of another service sharing the VPN
    qbittorrent:
        image: ghcr.io/linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Rome
            - WEBUI_PORT=8081
        volumes:
            - /yacht/AppData/Config/qBittorrent:/config
            - /data/Download:/downloads
        network_mode: "service:vpn"
        depends_on: [ "vpn", ]
        restart: unless-stopped
```
Must be adapted for username/password, location and volumes, but is working.
Now I'm trying to understand how works your bare-bone example, I already have a script to change qBittorrent port, but I've to adapt to docker style, so.
I added this to the docker-compose file
```
    deluge-port-helper:
        build: /yacht/AppData/Config/qBittorrent/Scripts
        volumes:
            - /yacht/AppData/Config/pia:/pia-shared:ro
        network_mode: "service:vpn"
        depends_on: [ "vpn", "qbittorrent", ]
```
I created a `Scripts` folder in `/yacht/AppData/Config/qBittorrent`, then inside `/yacht/AppData/Config/qBittorrent/Scripts` a `Dockerfile` with this content:
```
FROM alpine:latest
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/main/" >> /etc/apk/repositories && \
    apk add --no-cache bash curl
ADD pia-port.sh /Scripts/pia-port.sh
RUN chmod +x /Scripts/*.sh
CMD ["/Scripts/pia-port.sh"]
```
My script use only curl, so I modified the script, but I can't understand the path, `/Scripts` is correct? or have to be `/yacht/AppData/Config/qBittorrent/Scripts`?
If I try to run the docker-compose file 
`Bad Request: build path /yacht/AppData/Config/qBittorrent/Scripts either does not exist, is not accessible, or is not a valid URL.`
The last script is `pia-port.sh`
```
#!/bin/bash

trap 'exit 0' SIGTERM

############ CONFIGURATION ############
oldport=0
port=0
#######################################
qbt_host="http://localhost" # qbittorrent machine?
qbt_username="admin" # Username for qbittorrent remote machine
qbt_password="adminadmin" # Password for qbittorrent remote machine
qbt_port="8081" # Port for qbittorrent webui
############ CONFIGURATION ############

############ FUNCTIONS ############
get_cookie () { # get the cookie
	echo "Getting cookie ..."
	qbt_cookie=$($curl_bin --silent --fail --show-error \
		--header "Referer: ${qbt_host}:${qbt_port}" \
		--cookie-jar - \
		--request GET "${qbt_host}:${qbt_port}/api/v2/auth/login?username=${qbt_username}&password=${qbt_password}")
	echo "done"
}
############ FUNCTIONS ############

while true
do
	[ -r "/pia-shared/port.dat" ] && port=$(cat /pia-shared/port.dat)

	if [ $oldport -ne $port ]; then

		get_cookie

		echo echo "$qbt_cookie" | $curl_bin --silent --fail --show-error \
			--cookie - \
			--request POST "${qbt_host}:${qbt_port}/api/v2/app/setPreferences" \
			--data 'json={"listen_port": "'"$port"'"}'
		sleep 1

		oldport=$port
	fi
	sleep 30 &
	wait $!
done
```
There's a way to use all variables from qBittorrent docker or I've to set it manually inside the script?

J
