### ISSUE TITLE
Communicate vpn-internal docker with vpn-external docker

### ISSUE THREAD

**Issue by Jorman** [thrnz/docker-wireguard-pia#24]
Hi, I was successfully set-up Pia-wireguard + qBittorrent + Port-forward script, now I'm trying to configure others containers but I've some difficulties, I need to reach qBittorrent from another docker that is not under vpn.
So If I point to Pia-wireguard ip, I can't get reply.
The Wireguard-Pia is under 172.24.0.1, qBittorrent is under 172.24.0.2, and other container is under 172.17.0.8, so I also tried to set `LOCAL_NETWORK=172.17.0.0/24` but without lucky

Any help/suggestion?

**Comment by thrnz** [comment]
As long as the containers are attached to the same Docker network, they should be able to communicate with each other in the normal way. An example ```docker-compose.yml``` might be something like:


```
version: '3'
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        networks:
            - example-network

    # Example of another service sharing the VPN connection
    bittorrent-client:
        image: some-bittorrent-client
        network_mode: "service:vpn"

    # Example of another service that isn't using the VPN but can still 
    # communicate with services that are. For example, bittorrent-client's
    # web-ui might be found at http://vpn:8080 from within this container
    reverse-proxy:
        image: some-reverse-proxy
        networks:
            - example-network

networks:
    example-network:
```
