### ISSUE TITLE
Fatal error on Synology 

### ISSUE THREAD

**Issue by NGDM** [thrnz/docker-wireguard-pia#39]
I'm encountering the same issue as in #31 

This is my log output:
```
[#] iptables-restore -n
[#] ip -4 rule delete table 51820
iptables-restore v1.8.7 (legacy): iptables-restore: unable to initialize table 'raw'
Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
[#] resolvconf -d wg0 -f
[#] ip link delete dev wg0
Wed Feb  2 22:41:18 UTC 2022: Fatal error
```

This is my compose:
```
wireguard:
    container_name: wireguard-pia
    image: thrnz/docker-wireguard-pia:latest
    volumes:
      - $DOCKER_PATH/wireguard-pia/config/:/pia
      - $DOCKER_PATH/wireguard-pia/port:/pia-shared
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LOC=swiss
      - USER=$PIA_USER
      - PASS=$PIA_PWD
      - LOCAL_NETWORK=192.168.0.0/24
      - PORT_FORWARDING=1
      - PORT_PERSIST=1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    network_mode: bridge
    privileged: true
    restart: always
```

I've tried adding/removing the `cap_add: - NET_ADMIN`, `privileged: true` and `WG_USERSPACE=1` but to no avail.

This is running on a Synology machine with kernel 3.10 so I installed the runfalk/synology-wireguard package beforehand and rebooted the machine.

Anything else I can try?
