### ISSUE TITLE
Off topic: privoxy

### ISSUE THREAD

**Issue by That-Dude** [thrnz/docker-wireguard-pia#43]
I have this docker working great on my rpi4 with this docker-compose:

```
version: '3'
services:
  vpn:
#    networks:
#      wg-vpn:
    image: thrnz/docker-wireguard-pia
    cap_add:
      - NET_ADMIN
    environment:
      - LOC=swiss
      - USER_FILE=/run/secrets/pia_username
      - PASS_FILE=/run/secrets/pia_password
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    secrets:
        - pia_username
        - pia_password

secrets:
    pia_username:
        file: /opt/pia/pia_user_file
    pia_password:
        file: /opt/pia/pia_pass_file
```

I was wondering if anyone could assist me with adding a Privoxy docker to my compose file to proxy traffic through this wireguard connection? My goal is to have an http proxy on port 8118 on the rpi's LAN IP address.

Apologies is this off-topic.

**Comment by thrnz** [comment]
I'm not familiar with Privoxy in particular, but I've used the following before to provide a SOCKS proxy to other machines on the lan. Hopefully it's easy enough to modify for use with Privoxy. The important bits are `network_mode` so the two containers share the same network stack, exposing the proxy server's `ports` on the vpn container rather than the proxy server one, and making sure the `LOCAL_NETWORK` env var is set correctly so the vpn container has access to the lan.

```
version: '3'
services:

    vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            - pia-dat:/pia
        ports:
            - 1080:1080
        cap_add:
            - NET_ADMIN
        secrets:
            - pia_username
            - pia_password
        environment:
            - LOCAL_NETWORK=192.168.1.0/24
            - LOC=swiss
            - USER_FILE=/run/secrets/pia_username
            - PASS_FILE=/run/secrets/pia_password
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
            
    socks-proxy:
        image: serjs/go-socks5-proxy
        network_mode: "service:vpn"

secrets:
    pia_username:
        file: ../secrets/pia_user
    pia_password:
        file: ../secrets/pia_pass

volumes:
    pia-dat:
```
