### ISSUE TITLE
QNAP QTS 5.0 "iptables-restore v1.8.8 (legacy): iptables-restore: unable to initialize table 'raw'"

### ISSUE THREAD

**Issue by kosgitcat** [thrnz/docker-wireguard-pia#49]
I have recently upgraded my home server to a QNAP TVS-h1688X NAS/Server and am currently porting over all of my docker containers, however I am running into an issue getting this docker container running on the new server.

Here is my compose.yml
```
---
version: '3'
services:
  vpn:
    image: thrnz/docker-wireguard-pia
    container_name: vpn
    cap_add:
      - NET_ADMIN
    volumes:
      - '/share/Docker/config/vpn/pia:/pia'
      - '/share/Docker/config/vpn/wireguard:/etc/wireguard'
      - '/dev/net/tun:/dev/net/tun'
    environment:
      - PUID=(redacted)
      - GUID=(redacted)
      - TZ=America/Chicago
      - LOC=ca_ontario
      - USER=(redacted)
      - PASS=(redacted)
      - PORT_FORWARDING=1
      - FIREWALL=1
      - KEEPALIVE=25
      - EXIT_ON_FATAL=1
      - LOCAL_NETWORK=192.168.0.0/16
      - PORT_FILE=/pia/forwarded_port
    ports:
      - '(redacted)' #deluge
      - '(redacted)' #delugedaemon
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    privileged: true
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
```

Here is the error that I am encountering when spinning the container up:
```
Warning: `/etc/wireguard/wg0.conf' is world accessible
wg-quick: `wg0' is not a WireGuard interface
Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: ca_ontario, cn: ontario411, ip: (redacted)
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Port forwarding is available at this location
Successfully generated /etc/wireguard/wg0.conf
Sun Jun  5 15:24:06 UTC 2022: Bringing up WireGuard interface wg0
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add (redacted) dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
iptables-restore v1.8.8 (legacy): iptables-restore: unable to initialize table 'raw'

Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
Sun Jun  5 15:24:06 UTC 2022: Fatal error
```

While the compose file hasn't changed from one server to the next, and it was running successfully on the old server, nevertheless I've tried using `- NFTABLES=1`, `WG_USERSPACE=1` and even `- ALLOWEDIPS=0.0.0.0/1,128.0.0.0/1` even though I do not think that latter is implemented here.
I've also tried multiple other potential solutions outside modifying the compose.yml file, of which I couldn't begin to remember, none of which had any change on the results here. 

I'm afraid I'm at a complete loss as to where to go from here.
