### ISSUE TITLE
Accessing ports routed via docker

### ISSUE THREAD

**Issue by mfizz1** [thrnz/docker-wireguard-pia#52]
I have a unique setup where I use zerotier to access my home network (part of a larger network). I also have this docker-wireguard-pia to route other container traffic through here. 

The containers outside of this connected on bridge / host I am able to access typing in my zerotier address (e.g. portainer jellyfin etc.) However, ports that I am routing through the docker I cannot access outside using zerotier IP. 

For example I should be able to access plex via `192.168.10.2:32400/web` just like I am able to access portainer via `192.168.10.2:9000`

How can I expose the ports being routed through this docker. I have already added the ip. From what it looks like I can access it locally because I am remote at the moment I ssh into my server and can curl using localhost / local network ip address.

```
version: "3"
services:
  pia-wg:
    container_name: vpn
    privileged: true
    image: thrnz/docker-wireguard-pia
    volumes:
      # Auth token is stored here
      - pia:/pia
      # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
      - pia-shared:/pia-shared
    cap_add:
      - NET_ADMIN
      # SYS_MODULE might not be needed with a 5.6+ kernel?
      - SYS_MODULE
    # Mounting the tun device may be necessary for userspace implementations
    #devices:
    #  - /dev/net/tun:/dev/net/tun
    environment:
      # The following env vars are required:
      - LOC=uk
      - USER=xx
      - PASS=yy
      # The rest are optional:
      - LOCAL_NETWORK=192.168.0.0/24
      #- KEEPALIVE=25
      #- VPNDNS=8.8.8.8,8.8.4.4
      #- PORT_FORWARDING=1
      #- WG_USERSPACE=1
    ports:
      - 8000:8000 #pyload
      - 32400:32400 #plex
      #- :
    sysctls:
      # wg-quick fails to set this without --privileged, so set it here instead if needed
      - net.ipv4.conf.all.src_valid_mark=1
      # May as well disable ipv6. Should be blocked anyway.
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    # The container has no recovery logic. Use a healthcheck to catch disconnects.
    healthcheck:
      test: ping -c 1 8.8.8.8 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
```
