### ISSUE TITLE
No external access from K8s Pod Container

### ISSUE THREAD

**Issue by mattkrass** [thrnz/docker-wireguard-pia#63]
I'm trying to run this image in a K8s pod in my home cluster, it starts and up and connects to PIA fine, but the container can't talk to anything but the internal K8s network. 

Here is my configuration for the workload:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pia-client
  namespace: vpn-apps
spec:
  serviceName: pia-client
  selector:
    matchLabels:
      app: pia-client
  template:
    metadata:
      labels:
        app: pia-client
    spec:
      containers:
      - name: pia-client
        image: thrnz/docker-wireguard-pia:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: LOC
            value: us_new_hampshire-pf
          - name: USER
            valueFrom:
              secretKeyRef:
                name: pia-secret
                key: PIA_USERNAME
          - name: PASS
            valueFrom:
              secretKeyRef:
                name: pia-secret
                key: PIA_PASSWORD
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: '1'
          - name: net.ipv6.conf.default.disable_ipv6
            value: '1'
          - name: net.ipv6.conf.all.disable_ipv6
            value: '1'
          - name: net.ipv6.conf.lo.disable_ipv6
            value: '1'
```

Output of `wg` command in container
```text
pia-client-0:/scripts# wg
interface: wg0
  public key: <redacted>
  private key: (hidden)
  listening port: 36892
  fwmark: 0xca6c

peer:  <redacted>
  endpoint: 154.6.13.131:1337
  allowed ips: 0.0.0.0/0
  transfer: 0 B received, 6.36 KiB sent
```

Container output:
```text
Fri Feb 17 22:39:01 UTC 2023: Generating auth token
Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: us_new_hampshire-pf, cn: newhampshire401, ip: 154.6.13.131
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Successfully generated /etc/wireguard/wg0.conf
Fri Feb 17 22:39:02 UTC 2023: Bringing up WireGuard interface wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.1.178.218 dev wg0
[#] ip link set mtu 1370 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n

interface: wg0
  public key: <redacted>
  private key: (hidden)
  listening port: 36892
  fwmark: 0xca6c

peer: <redacted>
  endpoint: 154.6.13.131:1337
  allowed ips: 0.0.0.0/0

Fri Feb 17 22:39:02 UTC 2023: WireGuard successfully started
Fri Feb 17 22:39:02 UTC 2023: Allowing network access to 10.42.4.8/24 on eth0
Fri Feb 17 22:39:02 UTC 2023: Firewall enabled: Blocking non-WireGuard traffic
```

Routing tables:
```text
pia-client-0:/scripts# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.42.4.1       0.0.0.0         UG    0      0        0 eth0
10.42.0.0       10.42.4.1       255.255.0.0     UG    0      0        0 eth0
10.42.4.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
pia-client-0:/scripts# ip -4 route list
default via 10.42.4.1 dev eth0
10.42.0.0/16 via 10.42.4.1 dev eth0
10.42.4.0/24 dev eth0 proto kernel scope link src 10.42.4.8
pia-client-0:/scripts# ip -4 route list table 51820
default dev wg0 scope link
pia-client-0:/scripts#
```

I've whitelisted all the `net.ipv4.*` and `net.ipv6.*` sysctls on my agents/servers. The `wg0` interface is present and has an IP assigned. Trying to ping, traceroute, lookup DNS, anything not on the local K8s network just fails.
