### ISSUE TITLE
Works for 4 minutes, then dies

### ISSUE THREAD

**Issue by CoreyVidal** [thrnz/docker-wireguard-pia#8]
Hey. Any idea why this might be happening?:

I have docker-wireguard-pia and I'm running a docker container of qBittorrent through it. It works fine at first and is super fast (50 MB/s down). All my external IP testing seems to show it's working properly. Then after exactly 4 minutes, the VPN dies.  No traffic can get through at all. qBittorrent shows 0 MB/s and everything is "stalled".

If I recreate qBittorrent and docker-wireguard-pia, it works again at first, and then dies after 4 minutes.

I've done extensive testing and can confirm the problem isn't with qBittorrent. docker-wireguard-pia's health pings return unhealthy.

Here's my compose:
```YAML
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE # SYS_MODULE might not be needed with a 5.6+ kernel?
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1 # wg-quick fails to set this without --privileged, so set it here instead if needed
      - net.ipv6.conf.default.disable_ipv6=1 # May as well disable ipv6. Should be blocked anyway.
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
      test: ping -c 1 ca.yahoo.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      t2_proxy:
        ipv4_address: $VPN_IP
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    # Mounting the tun device may be necessary for userspace implementations
    # devices: 
    #   - /dev/net/tun:/dev/net/tun
    volumes:
      - $DIR_DOCKER/vpn/pia:/pia # Auth token is stored here
      - $DIR_DOCKER/vpn/pia-shared:/pia-shared # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
    environment:
      - USER=$VPN_USERNAME
      - PASS=$VPN_PASSWORD
      - LOCAL_NETWORK=192.168.1.0/24 192.168.90.0/24 192.168.91.0/24
      # - VPNDNS=192.168.1.251
      # - PORT_FORWARDING=1
      - LOC=ca_toronto
      # - USEMODERN=1
      # - KEEPALIVE=25
      # - EXIT_ON_FATAL=0
      # - WG_USERSPACE=1
```
