### ISSUE TITLE
Fatal error on Synology

### ISSUE THREAD

**Issue by juanca** [thrnz/docker-wireguard-pia#84]
I'm attempting to run the docker image in my synology server via docker-compose. The same docker-compose file works on my development machine (m1 laptop) and mac pro 2013. 

Here is the relevant bits from the `docker-compose.yaml` file:

```yaml
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia:latest
    cap_add:
      - NET_ADMIN
    environment:
      LOC: mexico
      PASS_FILE: /config/pass
      USER_FILE: /config/user
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vpn
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    volumes:
      - ./vpn:/config:ro
```

Logs (bottom to top)

date | stream | content
-- | -- | --
2023-10-23T07:02:16.961001953Z | stdout | Mon Oct 23 07:02:16 UTC 2023: Fatal error
2023-10-23T07:02:16.959315077Z | stderr | Cannot find device "wg0"
2023-10-23T07:02:16.956866995Z | stderr | [#] ip link delete dev wg0
2023-10-23T07:02:16.956574515Z | stderr | Unable to access interface: Protocol not supported
2023-10-23T07:02:16.934974914Z | stdout | ERROR: (wg0) 2023/10/23 07:02:16 Failed to create TUN device: CreateTUN("wg0") failed; /dev/net/tun does not exist
2023-10-23T07:02:16.934914475Z | stderr | └──────────────────────────────────────────────────────┘
2023-10-23T07:02:16.934878114Z | stderr | │                                                      │
2023-10-23T07:02:16.934835425Z | stderr | │         https://www.wireguard.com/install/           │
2023-10-23T07:02:16.934774507Z | stderr | │   please visit:                                      │
2023-10-23T07:02:16.934726574Z | stderr | │   information on installing the kernel module,       │
2023-10-23T07:02:16.934680339Z | stderr | │   kernel has first class support for WireGuard. For  │
2023-10-23T07:02:16.934618237Z | stderr | │   Running wireguard-go is not required because this  │
2023-10-23T07:02:16.934490910Z | stderr | │                                                      │
2023-10-23T07:02:16.933733412Z | stderr | ┌──────────────────────────────────────────────────────┐
2023-10-23T07:02:16.904576777Z | stderr | [#] wireguard-go wg0
2023-10-23T07:02:16.904527087Z | stderr | [!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
2023-10-23T07:02:16.904486789Z | stderr | RTNETLINK answers: Not supported
2023-10-23T07:02:16.840086886Z | stderr | [#] ip link add wg0 type wireguard
2023-10-23T07:02:16.904337119Z | stdout | Mon Oct 23 07:02:16 UTC 2023: Bringing up WireGuard interface wg0
2023-10-23T07:02:16.904280759Z | stdout | Successfully generated /etc/wireguard/wg0.conf
2023-10-23T07:02:16.904190636Z | stdout | Port forwarding is available at this location
2023-10-23T07:02:16.258399863Z | stdout | Using PIA DNS servers: 10.0.0.243,10.0.0.242
2023-10-23T07:02:16.168374820Z | stdout | Generating /etc/wireguard/wg0.conf
2023-10-23T07:02:15.484133734Z | stdout | Registering public key with PIA endpoint; id: mexico, cn: mexico414, ip: 77.81.142.249
2023-10-23T07:02:15.098262181Z | stdout | Verified server list
2023-10-23T07:02:15.096756499Z | stdout | Verified OK
2023-10-23T07:02:13.867277339Z | stdout | Fetching next-gen PIA server list
2023-10-23T06:58:02.555554552Z | stderr | wg-quick: `/etc/wireguard/wg0.conf' does not exist
2023-10-23T06:58:02.262994858Z | stdout | Mon Oct 23 06:58:02 UTC 2023: Shutting down WireGuard
2023-10-23T06:32:24.216480581Z | stdout | Mon Oct 23 06:32:24 UTC 2023: Fatal error
2023-10-23T06:32:24.216427145Z | stdout | Mon Oct 23 06:32:24 UTC 2023: Failed to generate WireGuard config for the selected location/s: mexico
2023-10-23T06:32:24.216335829Z | stdout | Mon Oct 23 06:32:24 UTC 2023: Registration failed
2023-10-23T06:32:24.129023936Z | stdout | WG key registration failed
2023-10-23T06:32:23.985305391Z | stderr | curl: (7) Failed to connect to mexico403 port 1337 after 25 ms: Couldn't connect to server
2023-10-23T06:32:23.953714536Z | stdout | Registering public key with PIA endpoint; id: mexico, cn: mexico403, ip: 77.81.142.15
2023-10-23T06:32:23.570745414Z | stdout | Verified server list
2023-10-23T06:32:23.569779583Z | stdout | Verified OK
2023-10-23T06:32:23.157000752Z | stdout | Fetching next-gen PIA server list
2023-10-23T06:32:22.491945752Z | stdout | Mon Oct 23 06:32:22 UTC 2023: Generating auth token
2023-10-23T06:32:22.490066050Z | stdout | Mon Oct 23 06:32:22 UTC 2023: Reading password from /config/pass
2023-10-23T06:32:22.487673321Z | stdout | Mon Oct 23 06:32:22 UTC 2023: Reading username from /config/user

I'm not sure what to google based on these logs. I tried a couple of things and some results indicate to download some "wireguard" package on the synology device. I searched but couldn't really find any packages -- but maybe I'm doing it wrong.

Anyone got any advice? Or got it to work on a synology device?

**Comment by thrnz** [comment]
> `ERROR: (wg0) 2023/10/23 07:02:16 Failed to create TUN device: CreateTUN("wg0") failed; /dev/net/tun does not exist`

That might be the issue. I've not needed to do it myself, but I understand that adding the `/dev/net/tun` device might be needed if Wireguard isn't natively supported. Something like this might work:

```
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia:latest
    cap_add:
      - NET_ADMIN
    environment:
      LOC: mexico
      PASS_FILE: /config/pass
      USER_FILE: /config/user
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vpn
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    volumes:
      - ./vpn:/config:ro
    devices:
      - /dev/net/tun:/dev/net/tun
```
